stages:
  data_ingestion:
    cmd: python src/fire_image_classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/fire_image_classifier/pipeline/stage_01_data_ingestion.py
      - src/fire_image_classifier/conf/config.yaml
    outs:
      - artifacts/data_ingestion/fire_dataset


  prepare_base_model:
    cmd: python src/fire_image_classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/fire_image_classifier/pipeline/stage_02_prepare_base_model.py
      - src/fire_image_classifier/conf/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/fire_image_classifier/pipeline/stage_03_model_trainer.py
    deps:
      - src/fire_image_classifier/pipeline/stage_03_model_trainer.py
      - src/fire_image_classifier/components/prepare_callbacks.py
      - src/fire_image_classifier/conf/config.yaml
      - artifacts/data_ingestion/fire_dataset
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - LEARNING_RATE
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/fire_image_classifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/fire_image_classifier/pipeline/stage_04_model_evaluation.py
      - src/fire_image_classifier/conf/config.yaml
      - artifacts/data_ingestion/fire_dataset
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false